### ISSUE TITLE
Error restarting job when the file name differs from the attribute id. Using jdbc repository

### ISSUE THREAD

**Issue by jlaborde4445** [jberet/jsr352#46] opened 2015-04-07 13:37 UTC
In the restart method (JobOperatorImpl) if the repository does not found the job ```repository.getJob(jobName)```, it tries to load the job from the file. If the job name is different from the xml file name, the job file is not found.
Example:
META-INF/batch-jobs/calculate-interest.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<job id="jbci" xmlns="http://xmlns.jcp.org/xml/ns/javaee" version="1.0">
```

Steps to reproduce error:

1. Start Job and end the job with error or stop job only

    > http://localhost:8080/batch-issuer/api/batch/start?name=jbci
    return executionId;
    ```
    public enum EJobsName implements IJobsName
   {
       jbci("calculate-interest", false, true);
    ```
2. Stop server

3. Start server

4. Restart the job 

> http://localhost:8080/batch-issuer/api/batch/restart?executionId=XXX

The problem is in class JobOperatorImpl.java, with the following lines

### Code
```
// the job may not have been loaded, e.g., when the restart is performed in a new JVM
final String jobName = originalToRestart.getJobName();
if (repository.getJob(jobName) == null) {
    final Job jobDefined = ArchiveXmlLoader.loadJobXml(jobName,  batchEnvironment.getClassLoader(), new ArrayList<Job>());
     repository.addJob(jobDefined);
}
```
### StackTrace:
>[ Message ] : FileNotFoundException: jbci.xml (El sistema no puede encontrar el archivo especificado)
[ Class  ]  : org.jberet.creation.ArchiveXmlLoader
[ Method ]  : loadJobXml
[ Parameters ]  : empty
[ Detail ]  : java.io.FileNotFoundException: jbci.xml (El sistema no puede encontrar el archivo especificado)
        at java.io.FileInputStream.open(Native Method) [rt.jar:1.7.0_75]
        at java.io.FileInputStream.<init>(FileInputStream.java:146) [rt.jar:1.7.0_75]
        at org.jberet.creation.ArchiveXmlLoader.getJobXml(ArchiveXmlLoader.java:145) [jberet-core-1.0.2.Final.jar:1.0.2.Final]
        at org.jberet.creation.ArchiveXmlLoader.loadJobXml(ArchiveXmlLoader.java:86) [jberet-core-1.0.2.Final.jar:1.0.2.Final]
        at org.jberet.operations.JobOperatorImpl.restart(JobOperatorImpl.java:205) [jberet-core-1.0.2.Final.jar:1.0.2.Final]

**Comment by chengfang** [comment] 2015-04-07 16:03
Need to fix the restart to correctly locate the job xml to load.

The best practice is to always keep job name and xml file name the same, similar to java class name and java file name.

Batch spec discussion:
https://java.net/projects/jbatch/lists/public/archive/2013-07/message/28

**Comment by jlaborde4445** [comment] 2015-04-07 17:29
Ok, but this error only occurs when the server is restarted, on normaly scenary the system works fine.
You could store this information in JOB_INSTANCE table and then the restart method could load the information from this table if the repository can't find it.

**Comment by chengfang** [comment] 2015-04-07 18:10
Changing ddl will cause compatibility issues with old job repository and jberet versions, and so we should avoid it.  Another option is to store it in JOB_EXECUTION table as an internal job parameters.

**Comment by jlaborde4445** [comment] 2015-04-07 20:13
Yes, this is a better solution since it will not affect the compatibility of jberet.

**Comment by chengfang** [comment] 2015-04-08 03:24
added tests to reproduce this issue:
https://github.com/chengfang/wildfly-samples/tree/master/jberet/deserialization

﻿org.jberet.testapps.deserialization.DeserializationIT#startJobNameDifferent
org.jberet.testapps.deserialization.DeserializationIT#restartJobNameDifferent

**Comment by chengfang** [comment] 2015-04-08 15:04
One complication with using job parameters to store jobXmlName is, currently we dont' need to save job parameters upon completion of the job execution, since job parameters are already saved in db when creating the job execution and won't change.  With the above proposal, we will need to be careful to update job parameter db column only if needed (only if it FAILED or STOPPED and jobXmlName differs from jobId).

**Comment by jlaborde4445** [comment] 2015-04-08 15:36
It's correct, this case occurs only when the job stops or fails, in other case is not necessary to store this internal information.

Other option, is to send in restart method one internal property to indicate the xmlJobName.

##### example: jberet.xmlJobName

```java
operator.restart(lastExecution.getExecutionId(), getParametersRestart(job, lastExecution));

private Properties getParametersRestart(IJobsName job, JobExecution execution) throws VfException
    {
        Properties props = execution.getJobParameters();
        **props.setProperty("jberet.xmlJobName", job.getXmlJobName());**
        if (job.allowLog()) {
            props.setProperty(JobParams.EXECUTION, String.valueOf(jobNames.getExecution(job)));
        }
        return props;
    }
```

**Comment by chengfang** [comment] 2015-04-09 01:20
Fixed in JBeret, and the fix will show up in WildFly 9 once jberet-core 1.1.0.Beta2 is integrated into WildFly.  Dropping current jberet-core snapshot jar into current WildFly 9 snapshot build will not work due to some other jberet changes.

**Closed by chengfang** 2015-04-09 01:20 UTC
